bpm = 111

loadstring(game:HttpGet("https://raw.githubusercontent.com/hellohellohell012321/TALENTLESS/main/loader_main.lua", true))()

keypress("f", 2, bpm)
keypress("t", 2, bpm)
rest(4, bpm)
keypress("s", 2, bpm)
keypress("t", 2, bpm)
rest(4, bpm)
keypress("p", 2, bpm)
keypress("w", 2, bpm)
rest(4, bpm)
keypress("u", 2, bpm)
keypress("t", 2, bpm)
rest(4, bpm)
keypress("s", 2, bpm)
keypress("e", 2, bpm)
rest(4, bpm)
keypress("s", 2, bpm)
keypress("W", 2, bpm)
rest(4, bpm)
keypress("p", 2, bpm)
keypress("w", 2, bpm)
rest(4, bpm)
keypress("s", 2, bpm)
keypress("Q", 2, bpm)
rest(4, bpm)
keypress("s", 2, bpm)
keypress("q", 2, bpm)
rest(4, bpm)
keypress("p", 2, bpm)
keypress("q", 2, bpm)
rest(4, bpm)
keypress("f", 2, bpm)
keypress("0", 2, bpm)
rest(4, bpm)
keypress("h", 2, bpm)
keypress("W", 2, bpm)
rest(2, bpm)
keypress("z", 2, bpm)
rest(2, bpm)
keypress("x", 3.5, bpm)
keypress("o", 4, bpm)
keypress("8", 4.75, bpm)
keypress("f", 4.75, bpm)
keypress("s", 4.75, bpm)
rest(3, bpm)
keypress("z", 1, bpm)
rest(1, bpm)
keypress("d", 4, bpm)
keypress("v", 4, bpm)
keypress("h", 4.75, bpm)
keypress("o", 4.75, bpm)
keypress("1", 12, bpm)
rest(4, bpm)
keypress("j", 3, bpm)
keypress("l", 4, bpm)
keypress("i", 4.75, bpm)
keypress("d", 4.75, bpm)
rest(3, bpm)
keypress("j", 1, bpm)
rest(1, bpm)
keypress("s", 4, bpm)
keypress("8", 4, bpm)
keypress("f", 4, bpm)
keypress("o", 4, bpm)
keypress("x", 4, bpm)
rest(3, bpm)
keypress("z", 1, bpm)
rest(1, bpm)
keypress("l", 2, bpm)
keypress("p", 4, bpm)
keypress("s", 4, bpm)
keypress("f", 4, bpm)
keypress("6", 4.75, bpm)
rest(4, bpm)
keypress("l", 2, bpm)
keypress("s", 4, bpm)
keypress("y", 4, bpm)
keypress("i", 4, bpm)
keypress("%", 4.75, bpm)
rest(4, bpm)
keypress("l", 2, bpm)
keypress("5", 4, bpm)
keypress("s", 4, bpm)
keypress("y", 4, bpm)
keypress("i", 4, bpm)
rest(2, bpm)
keypress("j", 2, bpm)
rest(2, bpm)
keypress("l", 2, bpm)
keypress("4", 4, bpm)
keypress("e", 4, bpm)
keypress("t", 4, bpm)
keypress("i", 4, bpm)
keypress("s", 4, bpm)
rest(4, bpm)
keypress("l", 2, bpm)
keypress("4", 4, bpm)
keypress("p", 4, bpm)
keypress("s", 4, bpm)
keypress("f", 4, bpm)
rest(2, bpm)
keypress("x", 2, bpm)
rest(2, bpm)
keypress("l", 2, bpm)
keypress("y", 4, bpm)
keypress("i", 4, bpm)
keypress("s", 4, bpm)
keypress("4", 4.75, bpm)
rest(2, bpm)
keypress("j", 2, bpm)
rest(2, bpm)
keypress("h", 2, bpm)
keypress("d", 4, bpm)
keypress("5", 4, bpm)
keypress("y", 4, bpm)
keypress("o", 4, bpm)
rest(4, bpm)
keypress("5", 4, bpm)
keypress("r", 4, bpm)
keypress("y", 4, bpm)
keypress("o", 4, bpm)
keypress("a", 4, bpm)
rest(4, bpm)
keypress("l", 2, bpm)
keypress("p", 4, bpm)
keypress("s", 4, bpm)
keypress("f", 4, bpm)
keypress("6", 4.75, bpm)
rest(4, bpm)
keypress("l", 2, bpm)
keypress("s", 4, bpm)
keypress("y", 4, bpm)
keypress("i", 4, bpm)
keypress("%", 4.75, bpm)
rest(4, bpm)
keypress("l", 2, bpm)
keypress("5", 4, bpm)
keypress("s", 4, bpm)
keypress("y", 4, bpm)
keypress("i", 4, bpm)
rest(2, bpm)
keypress("j", 2, bpm)
rest(2, bpm)
keypress("l", 2, bpm)
keypress("4", 4, bpm)
keypress("e", 4, bpm)
keypress("t", 4, bpm)
keypress("i", 4, bpm)
keypress("s", 4, bpm)
rest(4, bpm)
keypress("2", 4.25, bpm)
keypress("9", 4.25, bpm)
keypress("e", 4.25, bpm)
keypress("j", 4.25, bpm)
rest(2, bpm)
keypress("l", 4.25, bpm)
rest(2, bpm)
keypress("5", 4.25, bpm)
keypress("y", 4.25, bpm)
keypress("k", 4.25, bpm)
rest(2, bpm)
keypress("h", 4.25, bpm)
rest(2, bpm)
keypress("9", 4.25, bpm)
keypress("g", 4.25, bpm)
rest(4, bpm)
keypress("q", 4, bpm)
keypress("e", 4, bpm)
rest(4, bpm)
keypress("h", 2.75, bpm)
keypress("1", 4, bpm)
keypress("0", 4, bpm)
keypress("u", 4, bpm)
keypress("w", 4, bpm)
rest(2, bpm)
keypress("f", 2.75, bpm)
rest(2, bpm)
keypress("s", 2.75, bpm)
keypress("4", 4, bpm)
rest(2, bpm)
keypress("d", 2, bpm)
rest(1.5, bpm)
keypress("s", 0.5, bpm)
rest(0.5, bpm)
keypress("f", 2, bpm)
keypress("6", 4, bpm)
keypress("0", 4, bpm)
keypress("w", 4, bpm)
keypress("o", 4, bpm)
keypress("t", 4, bpm)
rest(2, bpm)
keypress("g", 2, bpm)
rest(1, bpm)
keypress("h", 2.75, bpm)
rest(1, bpm)
keypress("f", 2.75, bpm)
keypress("4", 4, bpm)
keypress("8", 4, bpm)
keypress("e", 4, bpm)
rest(4, bpm)
keypress("4", 3.5, bpm)
keypress("8", 3.5, bpm)
keypress("o", 3.5, bpm)
keypress("d", 3.5, bpm)
rest(3.75, bpm)
keypress("s", 0.25, bpm)
rest(0.125, bpm)
keypress("d", 0.25, bpm)
rest(0.125, bpm)
keypress("6", 3.5, bpm)
keypress("f", 3.5, bpm)
rest(4, bpm)
keypress("h", 3.5, bpm)
keypress("8", 3.5, bpm)
rest(2, bpm)
keypress("f", 3.5, bpm)
rest(2, bpm)
keypress("5", 3.5, bpm)
keypress("d", 3.5, bpm)
rest(2, bpm)
keypress("0", 2, bpm)
keypress("f", 2, bpm)
rest(2, bpm)
keypress("x", 3.5, bpm)
keypress("o", 4, bpm)
keypress("8", 4.75, bpm)
keypress("f", 4.75, bpm)
keypress("s", 4.75, bpm)
rest(3, bpm)
keypress("z", 1, bpm)
rest(0.5, bpm)
keypress("l", 0.5, bpm)
rest(0.5, bpm)
keypress("v", 4, bpm)
keypress("d", 4, bpm)
keypress("h", 4.75, bpm)
keypress("o", 4.75, bpm)
keypress("1", 12, bpm)
rest(3.5, bpm)
keypress("z", 0.5, bpm)
rest(0.5, bpm)
keypress("j", 3, bpm)
keypress("l", 4, bpm)
keypress("i", 4.75, bpm)
keypress("d", 4.75, bpm)
rest(3, bpm)
keypress("j", 1, bpm)
rest(0.5, bpm)
keypress("v", 0.25, bpm)
rest(0.25, bpm)
keypress("l", 0.25, bpm)
rest(0.25, bpm)
keypress("8", 4, bpm)
keypress("o", 4, bpm)
keypress("f", 4, bpm)
keypress("x", 4, bpm)
keypress("s", 4, bpm)
rest(3, bpm)
keypress("z", 1, bpm)
rest(1, bpm)
keypress("l", 2, bpm)
keypress("p", 4, bpm)
keypress("s", 4, bpm)
keypress("f", 4, bpm)
keypress("6", 4.75, bpm)
rest(4, bpm)
keypress("l", 2, bpm)
keypress("s", 4, bpm)
keypress("y", 4, bpm)
keypress("i", 4, bpm)
keypress("%", 4.75, bpm)
rest(4, bpm)
keypress("l", 2, bpm)
keypress("5", 4, bpm)
keypress("s", 4, bpm)
keypress("y", 4, bpm)
keypress("i", 4, bpm)
rest(2, bpm)
keypress("j", 2, bpm)
rest(2, bpm)
keypress("l", 2, bpm)
keypress("4", 4, bpm)
keypress("e", 4, bpm)
keypress("t", 4, bpm)
keypress("i", 4, bpm)
keypress("s", 4, bpm)
rest(4, bpm)
keypress("2", 4.25, bpm)
keypress("9", 4.25, bpm)
keypress("e", 4.25, bpm)
keypress("j", 4.25, bpm)
rest(2, bpm)
keypress("l", 4.25, bpm)
rest(2, bpm)
keypress("x", 4, bpm)
keypress("%", 4.25, bpm)
keypress("y", 4.25, bpm)
rest(2, bpm)
keypress("v", 4.25, bpm)
rest(2, bpm)
keypress("0", 4, bpm)
keypress("s", 4, bpm)
keypress("1", 4, bpm)
keypress("x", 4, bpm)
rest(4, bpm)
keypress("t", 16, bpm)
keypress("w", 16, bpm)
keypress("1", 16, bpm)

finishedSong()
